config/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.contrib.staticfiles.urls import staticfiles_urlpatterns
from django.urls import include, path

urlpatterns = [
    path("admin/", admin.site.urls),
    path("", include("ranked_choice.urls", "ranked_choice")),
]

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
urlpatterns += staticfiles_urlpatterns()

ranked_choice/urls.py
from django.urls import path

from . import views

app_name = "ranked_choice"

urlpatterns = [
    path("vote/<int:pk>", views.details, name="details"),
    path("", views.index, name="index"),
]

ranked_choice/models.py
from django.db import models
from django.utils.translation import gettext_lazy as _


class Vote(models.Model):
    """
    A ranked choice voting session
    """

    class Status(models.TextChoices):
        CREATED = "CR", _("Created")
        OPEN = "OP", _("Open")
        TALLYING = "TL", _("Tallying")
        CLOSED = "CL", _("Closed")

    class Meta:
        indexes = [models.Index(fields=["modified"])]

    name = models.CharField(max_length=128)
    status = models.CharField(
        max_length=2, choices=Status.choices, default=Status.CREATED
    )
    results = models.JSONField(blank=True, null=True)
    created = models.DateTimeField(auto_now_add=True)
    modified = models.DateTimeField(auto_now=True)

    vote_candidates = models.ManyToManyField("Candidate")

    def get_css_status_class(self):
        statuses = {
            self.Status.CREATED: "text-bg-success",
            self.Status.OPEN: "text-bg-info",
            self.Status.TALLYING: "text-bg-warning",
            self.Status.CLOSED: "text-bg-danger",
        }
        return statuses[self.status]

    def status_label(self):
        return Vote.Status(self.status).label


class Candidate(models.Model):
    """
    The thing to rank in a vote
    """

    name = models.CharField(max_length=255)
    image = models.ImageField(upload_to="candidates")

    def __str__(self):
        return f"<Candidate name={self.name} image={self.image.path}>"


class UserVote(models.Model):
    """
    The votes, unique per IP Address
    """

    vote = models.ForeignKey(Vote, on_delete=models.CASCADE, related_name="user_votes")
    ip_address = models.CharField(max_length=128)
    user_candidates = models.JSONField(null=True, blank=True)

    class Meta:
        indexes = [
            models.Index(fields=["ip_address", "vote"]),
        ]

ranked_choice/views.py
from django.shortcuts import get_object_or_404, render
from django.views.decorators.http import require_GET

from .models import Vote


@require_GET
def index(request):
    votes = Vote.objects.all().order_by("-modified")
    return render(request, "index.html", {"votes": votes})


@require_GET
def details(request, pk):
    vote = get_object_or_404(Vote, pk=pk)
    return render(request, "details.html", {"vote": vote})

ranked_choice/templates/details.html
{% extends 'layout.html' %}

{% load static %}
{% load tz %}

{% block content %}

<div class="container">
    <div class="row align-items-center p-4">
        <h1>{{ vote.name }}</h1>
    </div>
    <div class="row">
        <div class="col-1 text-bg-dark text-end rounded-top">
            <strong>Status</strong>
        </div>
        <div class="col-3 align-self-end text-end">
            <span class="badge {{ vote.get_css_status_class }}">{{ vote.status_label }}</span>
        </div>
    </div>

    <div class="row">
        <div class="col-1 text-bg-dark text-end">
            <strong>Created</strong>
        </div>
        <div class="col-3 text-end">{{ vote.created }}</div>
    </div>

    <div class="row">
        <div class="col-1 text-bg-dark text-end rounded-bottom">
            <strong>Modified</strong>
        </div>
        <div class="col-3 text-end">{{ vote.modified }}</div>
    </div>
</div>

<div class="container">
    <ul class="list-group shadow-sm">
        {% for candidate in vote.vote_candidates.all %}
            <li class="list-group-item shadow-sm">
                <img class="img-thumbnail" width="50" height="50" src="{{candidate.image.url}}"/>
                {{ candidate.name }}
            </li>
        {% endfor %}
    </ul>
</div>

{% endblock %}

ranked_choice/templates/index.html
{% extends 'layout.html' %}

{% load static %}
{% load tz %}

{% block content %}
<h1>Welcome to Ranked Choice Voting!</h1>

<h2>Current Votes:</h2>

{% for vote in votes %}
    <div class="card m-5" style="width: 20rem;">
        <div class="card-header">
            <h5 class="card-title">
                {{ vote.name }}
                <a href="{% url 'ranked_choice:details' pk=vote.pk %}" class="btn btn-secondary float-end">
                    <i class="bi-arrow-right-circle-fill"></i>
                </a>
            </h5>

        </div>
        <ul class="list-group list-group-flush">
            <li class="list-group-item">
                <b>Status: </b>
                <span class="badge {{ vote.get_css_status_class }}">
                    {{ vote.status_label }}
                </span>
            </li>
        </ul>
        <div class="card-footer text-body-secondary">
            <b>Last updated: </b>{{ vote.modified }}
        </div>
    </div>
{% endfor %}

{% endblock %}

ranked_choice/templates/layout.html
<!DOCTYPE html>
<html>
<head>
    <meta charset="UTF-8">
    <title>Ranked Choice</title>

    {% load static %}
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-QWTKZyjpPEjISv5WaRU9OFeRpok6YctnYmDr5pNlyT2bRjXh0JMhjY6hW+ALEwIH" crossorigin="anonymous">
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.11.3/font/bootstrap-icons.min.css">
    <link rel="stylesheet" href="{% static 'css/base.css' %}">
</head>

<body class="bg-bg p-16 bg-secondary-subtle" hx-boost="true" hx-headers='{"X-CSRFToken": "{{ csrf_token }}"}'>
    <nav class="navbar navbar-expand-lg navbar-dark bg-dark shadow-sm sticky-top">
        <div class="container-fluid">
            <a href="{% url 'ranked_choice:index' %}" class="navbar-brand">Ranked Choice</a>
            <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarNav" aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
                <span class="navbar-toggler-icon"></span>
            </button>
            <div class="collapse navbar-collapse" id="navbarNav">
                <ul class="navbar-nav">
                    <li class="nav-item">
                        <a href="{% url 'ranked_choice:index' %}" class="nav-link active" aria-current="page">Home</a>
                    </li>
                </ul>
            </div>
        </div>
    </nav>
    {% block content %}
    {% endblock content %}
    <script src="{% static 'js/htmx.js' %}" defer></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/js/bootstrap.bundle.min.js" integrity="sha384-YvpcrYf0tY3lHB60NNkmXc5s9fDVZLESaAA55NDzOxhy9GkcIdslK1eN7N6jIeHz" crossorigin="anonymous"></script>
    <script src="{% static 'js/site.js' %}"></script>
</body>
</html>